### ISSUE TITLE
Get the history behind Genomic-CDM efforts

### ISSUE THREAD

**Issue by meerapatelmd** [OHDSI/Genomic-CDM#5]
@chandryou @spooyaei

**Comment by cgreich** [comment]
Is there an issue here, @patelm9?

**Comment by meerapatelmd** [comment]
@cgreich There is interest in revisiting the genomics-CDM and I am centralizing our tasks/issues here as we work on getting everyone situated with the effort.

**Comment by meerapatelmd** [comment]
duplicative of new issue created within OncologyWG
